//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public System.Guid CartID { get; set; }
        public System.Guid CosmeticID { get; set; }
        public System.Guid UserID { get; set; }
        public int Amount { get; set; }
        public decimal Pay { get; set; }
    }
}
