//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid CommentID { get; set; }
        public System.Guid OrderDetailID { get; set; }
        public System.Guid UserID { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime CommentTime { get; set; }
        public string ParentComment { get; set; }
    }
}
