//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public System.Guid OrderListID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTel { get; set; }
        public string Addr { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<System.DateTime> ExpectTime { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid OrderDetailID { get; set; }
        public decimal TotalMoney { get; set; }
    }
}
