//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public string RecordID { get; set; }
        public Nullable<decimal> RechargeMoney { get; set; }
        public Nullable<System.DateTime> RechargeTime { get; set; }
        public Nullable<decimal> BeginMoney { get; set; }
        public Nullable<decimal> FinalMoney { get; set; }
        public Nullable<decimal> ExpendMoney { get; set; }
        public Nullable<System.DateTime> MachineTime { get; set; }
        public string Abstract { get; set; }
        public string Note { get; set; }
        public System.Guid UserID { get; set; }
    }
}
