//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmallMarketEntities : DbContext
    {
        public SmallMarketEntities()
            : base("name=SmallMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<供应商信息表> 供应商信息表 { get; set; }
        public virtual DbSet<入库表> 入库表 { get; set; }
        public virtual DbSet<商品信息表> 商品信息表 { get; set; }
        public virtual DbSet<销售表> 销售表 { get; set; }
    }
}
