//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid OrderDetailID { get; set; }
        public int CosmeticNum { get; set; }
        public decimal Price { get; set; }
        public System.Guid CosmeticID { get; set; }
        public System.Guid OrderListID { get; set; }
        public string Remark { get; set; }
    }
}
