//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品信息表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 商品信息表()
        {
            this.订单明细表 = new HashSet<订单明细表>();
        }
    
        public string 商品ID { get; set; }
        public string 商品名称 { get; set; }
        public string 商品类型名称 { get; set; }
        public decimal 商品单价 { get; set; }
        public int 商品库存 { get; set; }
        public string 商品规格 { get; set; }
        public string 商品描述 { get; set; }
        public string 商品品牌 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<订单明细表> 订单明细表 { get; set; }
        public virtual 商品类型表 商品类型表 { get; set; }
        
        
    }
}
