//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品评论表
    {
        public string 评论ID { get; set; }
        public string 商品ID { get; set; }
        public string 用户ID { get; set; }
        public string 评论内容 { get; set; }
        public System.DateTime 评论时间 { get; set; }
        public string 管理员ID { get; set; }
        public string 回复内容 { get; set; }
        public System.DateTime 回复时间 { get; set; }
    
        public virtual 管理员表 管理员表 { get; set; }
    }
}
