//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 商品类型表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 商品类型表()
        {
            this.商品信息表 = new HashSet<商品信息表>();
        }
    
        public string 商品类型名称 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<商品信息表> 商品信息表 { get; set; }
    }
}
