//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 用户表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 用户表()
        {
            this.订单表 = new HashSet<订单表>();
            this.购物车表 = new HashSet<购物车表>();
        }
    
        public string 用户ID { get; set; }
        public string 用户名 { get; set; }
        public string 登录密码 { get; set; }
        public string 手机号 { get; set; }
        public string 邮箱 { get; set; }
        public string 个人简介 { get; set; }
        public byte[] 头像 { get; set; }
        public Nullable<System.DateTime> 用户生日 { get; set; }
        public string 重置密码 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<订单表> 订单表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<购物车表> 购物车表 { get; set; }
    }
}
