//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 订单表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 订单表()
        {
            this.订单明细表 = new HashSet<订单明细表>();
        }
    
        public string 订单号 { get; set; }
        public string 收货人 { get; set; }
        public string 收货人电话 { get; set; }
        public string 收货人地址 { get; set; }
        public System.DateTime 订单时间 { get; set; }
        public System.DateTime 预计交货时间 { get; set; }
        public string 用户ID { get; set; }
        public string 账户记录ID { get; set; }
        public decimal 订单总金额 { get; set; }
    
        public virtual 用户表 用户表 { get; set; }
        public virtual 账户记录表 账户记录表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<订单明细表> 订单明细表 { get; set; }
    }
}
