//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 订单明细表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 订单明细表()
        {
            this.商品评论表 = new HashSet<商品评论表>();
        }
    
        public string 订单明细ID { get; set; }
        public int 商品数量 { get; set; }
        public string 商品ID { get; set; }
        public string 订单号 { get; set; }
        public decimal 商品单价 { get; set; }
        public string 备注 { get; set; }
    
        public virtual 订单表 订单表 { get; set; }
        public virtual 商品信息表 商品信息表 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<商品评论表> 商品评论表 { get; set; }
    }
}
