//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 账户记录表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 账户记录表()
        {
            this.订单表 = new HashSet<订单表>();
        }
    
        public string 账户记录ID { get; set; }
        public decimal 充值金额 { get; set; }
        public System.DateTime 充值日期 { get; set; }
        public decimal 期初金额 { get; set; }
        public decimal 期末金额 { get; set; }
        public decimal 支出金额 { get; set; }
        public System.DateTime 机器时间 { get; set; }
        public string 摘要 { get; set; }
        public string 备注 { get; set; }
        public string 用户ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<订单表> 订单表 { get; set; }
    }
}
