//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmeticsWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class 购物车表
    {
        public string 购物车ID { get; set; }
        public string 商品ID { get; set; }
        public string 用户ID { get; set; }
        public int 数量 { get; set; }
        public decimal 应付款 { get; set; }
    
        public virtual 用户表 用户表 { get; set; }
    }
}
